### ISSUE TITLE
train on my dataset

### ISSUE THREAD

**Issue by yanqian123** [yysijie/st-gcn#100]
@yysijie hi, i have used st-gcn to train on my dataset,after training ,i have an idea that i want to reduce the Length=300,bucause my videos are short about 2s~3s, so if i want to change the lengh=300 about GCN, what should i take notice??????thanks

**Comment by BigBugGrow** [comment]
@yanqian123 hello，I am doing something similar to yours，can I communicate with you on WeChat?

**Comment by yysijie** [comment]
@yanqian123,
Since there is a global pooling layer at the end of ST-GCN. You can feed sequences with arbitrary length. We do not observe considerable performance degradation or improvement when the input shape changes. We make length=300 because the maximal length of videos in Kinetics and NTU-RGB-D dataset is 300.

**Comment by yanqian123** [comment]
thanks for your reply!

**Comment by huangzhenjie** [comment]
@yanqian123 你好，我想训练自己的数据集，请问可以分享下如何把一个视频转换为输入json格式的脚本吗？非常感谢，我邮箱761005190@qq.com

**Comment by Tylerjoe** [comment]
@yanqian123 @yysijie If I train the model with my own dataset, but the size(width and height) of every video is different, how should edit the parameters , or it's not necessary to change any parameter? I glad to get your reply, Thanks!
