### ISSUE TITLE
Questions about the pre-training model

### ISSUE THREAD

**Issue by hd120105** [yysijie/st-gcn#124]
@yysijie @yjxiong ,hello, sorry to interrupt you, I am naive to ST-GCN and I have built my own dataset which is much smaller than kinetics, there are 99 classes. I use my dataset to fine-tune the pre-trained model you gave and modified num_classes in train.yaml, but with the following error:
Mismatch for fcn.weight:copying a param of torch.size([99,256,1,1]) from checkpoint,where the shape is torch.Size([400,256,1,1]) in current model
If you can, can you tell me where to fix this problem?Thank

**Comment by yjxiong** [comment]
It looks like the classifier weights are causing the problem. When finetuning, you should create a new classifier module instead of loading the one in the pretrained models.

**Comment by Sindreedelange** [comment]
@xiaoyuliu - Would've been great with a little more in-depth explanation. It seems like an issue that multiple people are facing, including myself. 

I would like to load the pretrained model (on the 400 classes) in order to utilize transfer learning for my 7 classes, but am stuck at how to load the weights, getting basically the same error message as @hd120105  (Did you ever figure this out?).

**Comment by nanhui69** [comment]
> It looks like the classifier weights are causing the problem. When finetuning, you should create a new classifier module instead of loading the one in the pretrained models.

how to load pretrained model in old version st-gcn base code to train new model?

**Comment by IlyesTal** [comment]
Hey guys!
I want to do a training on a custom dataset using ST-GCN, but I can't understand exactly how the dataset should look like. It seems that you overcame this issue, if someone can help me that would be amazing. I have data extracted from sport videos using OpenPose (25 keypoints).
