### ISSUE TITLE
[Person tracking] Is the order of detected persons preserved from frame t to frame t+1 ?

### ISSUE THREAD

**Issue by ahmedmazariML** [yysijie/st-gcn#158]
Hi @yysijie,

Following  your scripts of kinetics skeletons generation https://github.com/yysijie/st-gcn/blob/master/tools/kinetics_gendata.py , l wonder : 
1- If the order of 5 persons detected at each frame is preserved. In other term :  is person N°3  at frame t corresponds the person N°3 at time frame t+1. How do you do the tracking.

2- What if the persons at different frames are not the same ?

3- If you detect 5 persons at frame t and 3 persons at frame t+1 how do you track them ?

Thank you

**Comment by yysijie** [comment]
@ahmedmazariML, thank you for your interests in our work.
In the scirpt you mentioned, we processed data offline by this data feeder module: https://github.com/yysijie/st-gcn/blob/master/feeder/feeder_kinetics.py.
This data feeder provided simple tracking strategy, but in the action recognition, we did not observe obvious improvement brought by it. Thus, the default setting is no tracking. To utilize person tracking,
plsase set ```pose_matching=True```.
Instead of this, we sorted the pose in each frame according to their confidence score. It is simple but works. For more information, please refer to:
https://github.com/yysijie/st-gcn/blob/e7024ac16714d6d6ac911f7cfb2910aea1940b15/feeder/feeder_kinetics.py#L137-L142

**Comment by jingong** [comment]
If you detect 5 persons at frame t and 3 persons at frame t+1，so how many people are processing all the frames in the entire action sequence?

**Comment by yjxiong** [comment]
@jingong 

Only `num_person_out` out of 5 or 3 will be process in the current implementation. You are free to modify it to run it on every person.

**Comment by CompliceU** [comment]
Hello, don't know if you have completed the task of this change. @yjxiong
