### ISSUE TITLE
Kinetic dataset?

### ISSUE THREAD

**Issue by JasOlean** [yysijie/st-gcn#193]
### Dataset used
How many seconds do you use in one training clip? Is it for one action per clip and how many clips do you train for each action? And could you send me a sample of your input video file?

**Comment by daylightsaving2017** [comment]
The .csv file in the kinetics_train dataset has provided all the answers to your questions.

**Comment by daylightsaving2017** [comment]
@JasOlean

**Comment by JasOlean** [comment]
I did not find any csv file in kinetics_train dataset. I only found json file. But, if there may be 300 frames for one clip, how to know that is complete action or repeat action?

**Comment by daylightsaving2017** [comment]
@JasOlean Hi. You'd better have a look on the original kinetics dataset given by the official website. Here is the link: [](https://deepmind.com/research/open-source/open-source-datasets/kinetics/) and
[](https://deepmind.com/documents/66/kinetics_train.zip).

**Comment by daylightsaving2017** [comment]
@JasOlean About your second question, the truth indeed is like what you described but it is caused by the type of the classification task. That is to say, the performance shown by the action recognition algorithm mainly depends on how you make the dataset (e.g. clip lengths, labels). Therefore, the demo of the creators actually gives a scene recognition result by voting mechanism. However, the sequence results tracked with the skeleton in the demo are real action recognition.

**Comment by JasOlean** [comment]
Ok. I will look it. Thank you very much.

One more thing I want to know. Is there sampling and partition part in Graph.py to construct graph? If yes, for other action (not human skeleton, but hand), do I need to change graph or sampling in constructing graph for it?

**Comment by daylightsaving2017** [comment]
@JasOlean I am not very sure what specific task you are running. The only point I could tell you is the application field of this algorithm is not limited in the scope of human skeleton. It may perform any classification tasks for any feature points and edges like moving "skeleton". However, how good it can perform in your task cannot be guaranteed but iterative experiments and optimizations~~~Good luck!

**Comment by JasOlean** [comment]
Thank you for your kind answers.
